sonar.projectKey=collector-shop
sonar.projectName=Collector-Shop
sonar.sources=frontend,microservices
sonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**,**/build/**,**/coverage/**
sonar.sourceEncoding=UTF-8
